config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  ActiveAdmin.routes(self)

  resources :shop_beers

  resources :beers

  resources :shops
  resources :ratings
  resources :criterions

  resources :addresses

  devise_for :users, :controllers => { registrations: 'registrations' }
  resources :events

  resources :clubs
  resources :categories
  resources :producers

   root 'welcome#index'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    user ||= User.new # guest user (not logged in)
    if user.has_role?(:admin)
      #Admins
      can :manage, :all
    elsif user.has_role?(:user)
      can :create, Club
      can :create, Rating
      can :create, Criterion
      can :create, Shop
      can :create, Beer

      can :manage, Rating do |r|
        r.user_id == user.id
      end

      can :manage, Criterion do |c|
        c.rating.user_id == user.id
      end


      can :manage, Shop do |s|
       s.user_id == user.id
      end

      can :read, :all

      @clubs = Club.where(user_id: user.id)

      @clubs.each do |c|
          can :manage, c
          can :manage, Event
        end
    else
      can :read, :all

    end
    #can :create, Event, :user_id => user.id

    #

    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities

  end
end

app/models/address.rb
class Address < ActiveRecord::Base
  has_one :user
  has_one :club
  has_one :shop
  validates :street,:house_number,:city,:country,:postal_code, presence: true
end

app/models/beer.rb
class Beer < ActiveRecord::Base
  belongs_to :category
  belongs_to :producer
  has_many :shop_beers
  has_many :shops, through: :shop_beers
  has_many :ratings
  has_many :users, :through => :ratings
  accepts_nested_attributes_for :category, :producer
  mount_uploader :beerURL, ImageUploader
  #validates :title, :category_id, :producer_id, presence: true
end

app/models/beer_club.rb
class BeerClub < ActiveRecord::Base
  belongs_to :beer
  belongs_to :club
end

app/models/category.rb
class Category < ActiveRecord::Base
   has_many :beers
   validates :name, presence: :true
end

app/models/club.rb
class Club < ActiveRecord::Base
  has_many :beer_clubs
  has_many :beers, through:  :beer_clubs
  has_many :events
  belongs_to :address
  belongs_to :user
  accepts_nested_attributes_for :address, :beers, :user
  mount_uploader :clubURL, ImageUploader

end

app/models/criterion.rb
class Criterion < ActiveRecord::Base
  belongs_to :rating
  validates :value ,:inclusion => 1..5
end

app/models/event.rb
class Event < ActiveRecord::Base
  belongs_to :club
  mount_uploader :imageURL, ImageUploader
  accepts_nested_attributes_for :club
  #validates :club_id, :title, presence: true
  validates :club_id, presence: true
  before_destroy :remember_image
  after_destroy :remove_img

  protected
  def remember_image
    @image_name = self[:imageURL]
  end

  def remove_img
    if @image_name.present?
      if File.exist?(@image_name)
        File.delete(@image_name)
      end
    end
  end

end

app/models/producer.rb
class Producer < ActiveRecord::Base
  belongs_to :address
  has_many :beers
  #validates :name, :address_id, presence: :true
  accepts_nested_attributes_for :address
end

app/models/rating.rb
class Rating < ActiveRecord::Base
  has_many :criterions
  belongs_to :user
  belongs_to :beer
  accepts_nested_attributes_for :criterions
  validates :headline,:comment, presence: true
  validates_associated :criterions
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users, :join_table => :users_roles
  belongs_to :resource, :polymorphic => true
  
  scopify
end

app/models/shop.rb
class Shop < ActiveRecord::Base

  has_many :shop_beers
  has_many :beers, through: :shop_beers
  belongs_to :user
  belongs_to :address
  validates :name,:email,:phonenumber,:website, presence: true
  validates_associated :address
  accepts_nested_attributes_for :address, :user
end

app/models/shop_beer.rb
class ShopBeer < ActiveRecord::Base
  belongs_to :shop
  belongs_to :beer
end

app/models/user.rb
class User < ActiveRecord::Base
  rolify
  belongs_to :address
  has_many :ratings
  has_many :beers, :through => :ratings
  has_many :clubs
  has_many :shops
  accepts_nested_attributes_for :address

  validates :first_name,:last_name, presence: true
  validates_associated :address


  after_create :assign_default_role

  def assign_default_role
    add_role(:user)
  end

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/shops_controller.rb
class ShopsController < ApplicationController
  before_action :set_shop, only: [:show, :edit, :update, :destroy]
  load_and_authorize_resource except: :create



  def index
    @shops = Shop.where(active: true)
    @shops_activ = Shop.where(active: false)

  end

  def show
  end

  def new
    @shop = Shop.new
    @shop.build_address
  end

  def edit
  end

  def create
    @shop = Shop.new (shop_params)

    if (@shop.active == true and current_user.has_role? :admin)
      @shop.active = true
    else
      @shop.active = false
    end
    if (current_user.has_role? :admin)
      #@club.user = club_params.user <- so wars vorher thorsten
      @shop.user = User.find( shop_params[:user_id])
    else
      @shop.user = current_user
    end

    respond_to { |format|
      if @shop.save

        format.html { redirect_to @shop, notice: "Shop was successfully created." }
        format.json { render :show, status: :created, location: @shop }
      else
        format.html { render :new }
        format.json { render json: @shop.errors, status: :unprocessable_entity }
      end
    }
  end

  def update
    respond_to do |format|
      if @shop.update(shop_params)
        format.html { redirect_to shops_path, notice: 'Shop was successfully updated.' }
        format.json { render :index, status: :ok, location: @shop }
      else
        format.html { render :edit }
        format.json { render json: @shop.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @shop.address.destroy if @shop.address.present?
    @shop.destroy
    respond_to do |format|
      format.html { redirect_to shops_url, notice: 'Shop was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_shop
      @shop = Shop.find(params[:id])
    end

    def shop_params
      params.require(:shop).permit(:name, :user_id , :email, :phonenumber, :website, :active , address_attributes: [:city, :postal_code, :street, :house_number, :country], beer_ids: [] )
    end
end

app/helpers/beers_helper.rb
module BeersHelper
end

app/helpers/breadcrumb_helper.rb
module BreadcrumbHelper
  def ensure_navigation
    @navigation ||= [ { :title => 'Home', :url => '/' } ]
  end

  def navigation_add(title, url)
    ensure_navigation << { :title => title, :url => url }
  end

  def render_breadcrumb
    render :partial => 'shared/breadcrumb', :locals => { :nav => ensure_navigation }
  end
end

app/helpers/clubs_helper.rb
module ClubsHelper
end

app/helpers/events_helper.rb
module EventsHelper
  require 'carrierwave/processing/mini_magick'
end

app/helpers/producers_helper.rb
module ProducersHelper
end

app/helpers/ratings_helper.rb
module RatingsHelper
end

app/helpers/shops_helper.rb
module ShopsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/shops/_form.html.erb
<%= form_for(@shop, html: {role: "form", class: "reg-page"}) do |f| %>
    <% if @shop.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@shop.errors.count, "error") %> prohibited this shop from being saved:</h2>

          <ul>
            <% @shop.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <h3 align="center"><% if current_page?(controller: shops_path, action: 'edit', id: params[:id] || 0 ) %>Edit Shop: <%= @shop.name %><%else%>Create a new Shop<%end%></h3>

    <hr/>
    <%= f.hidden_field :user_id, :value => current_user.id %>
    <div class="controls">
      <%= f.label :name do %>
          Name<span class="color-red"> *</span>
      <% end %>
      <%= f.text_field :name, class: "span12" %>
    </div>


    <div class="controls">
      <%= f.fields_for :address do |info| %>
          <div class="fields">
            <div class="form-group">
              <div class="span7">
                <%= info.label :city do %>
                    City<span class="color-red"> *</span>
                <% end %>
                <%= info.text_field :city, class: "span12" %>
              </div>
            </div>

            <div class="span5">
              <%= info.label :postal_code do %>
                  Postal Code<span class="color-red"> *</span>
              <% end %>
              <%= info.text_field :postal_code, class: "span12" %>
            </div>

            <div class="form-group">
              <div class="span7">
                <%= info.label :street do %>
                    Street<span class="color-red"> *</span>
                <% end %>
                <%= info.text_field :street, class: "span12" %>
              </div>
            </div>

            <div class="span5">
              <%= info.label :house_number do %>
                  House number<span class="color-red"> *</span>
              <% end %>
              <%= info.text_field :house_number, class: "span12" %>
            </div>

            <div class="form-group">
              <%= info.label :country do %>
                  Country<span class="color-red"> *</span>
              <% end %>
              <%= info.text_field :country, class: "span12" %>
            </div>
          </div>
      <% end %>
    </div>


    <div class="controls">
      <div class="span7">
        <%= f.label :email %>
        <%= f.text_field :email, class: "span12" %>
      </div>

      <div class="span5">
        <%= f.label :phonenumber do %>
            Phone Number
        <% end %>
        <%= f.text_field :phonenumber, class: "span12" %>
      </div>
    </div>

    <div class="controls">
      <%= f.label :website do %>
          Website<span class="color-red"> *</span>
      <% end %>
      <%= f.text_field :website, class: "span12" %>
    </div>


    <div class="controls">
      <div class="view view-tenth span6">
        <%= f.label :beer do %>
            Beers<span class="color-red"> *</span>
        <% end %>
      </div>
      <div class="span6">
        <%= f.label :active %>
      </div>


      <div class="checkbox pull-left span6">
        <%= f.collection_check_boxes(:beer_ids, Beer.all, :id, :title) %>
        <hr/>
      </div>

      <div>
        <% if current_user.has_role? :admin %>
            <% if params[:active] = "true" %>
                <%= f.check_box :active, {:checked => true} %>
            <% else %>
                <%= f.check_box :active  %>
            <% end %>
        <% end %>
      </div>
    </div>

    <br>

    <div class="controls form-inline span12">
      <input type="checkbox">
      <label class="checkbox" style="padding-top: 4.5px; padding-left: 5px">
        I read <a class="color-green">Terms and Conditions</a>
      </label>
      <%= f.submit class: "btn-u pull-right" %>
    </div>

<% end %>

app/views/shops/edit.html.erb
<div class="body">

  <% content_for :title, 'Edit Shop' %>
  <% navigation_add 'Shop', shops_path %>

  <div class="container">
    <div class="row-fluid">

      <%= render 'form' %>

      <div class="glyphicons-demo" style="text-align: center">
        <a class="glyphicons no-js left_arrow" href=<%= shops_path %>><i></i>Back</a>
        <a class="glyphicons no-js file" href=<%= shop_path %>><i></i>Show</a>
      </div>
    </div>
  </div>
</div>

app/views/shops/index.html.erb
<% content_for :title, 'Shop' %>

<div class="container">
  <div class="row-fluid">
    <div class="row-fluid margin-bottom-20">
      <div class="booking-blocks">
        <div class="overflow-hidden">

          <div class="headline"><h3>All Shops</h3></div>

          <% if current_user %>
              <% if current_user.has_role? :admin %>
                  <% if @shops_activ.count == 0 %>
                      <div>Currently all Shops are activated.</div>
                  <% else %>
                      <table class="table table-hover">
                        <thead>
                        <tr>
                          <th>Name</th>
                          <th></th>
                        </tr>
                        </thead>
                        <tbody>
                        <% @shops_activ.each do |a| %>
                            <tr>
                              <td style="vertical-align:middle;white-space:nowrap;">
                                <%= a.name %>
                              </td>
                              <td width="100%"></td>
                              <td style="vertical-align:middle;white-space:nowrap; ">
                                <a class="btn btn-default btn-sm" href=<%= edit_shop_path(a, :active => true) %>><i class="fa fa-check"></i> Activate</a>
                              </td>
                            </tr>
                        <% end %>
                        </tbody>
                      </table>
                  <% end %>
              <% end %>
          <% end %>
          <table class="table table-hover">
            <thead>
            <tr>
              <th>#</th>
              <th>Name</th>
              <th>Address</th>
            </tr>
            </thead>

            <tbody>
            <% @count=1 %>
            <% @shops.each do |shop| %>
                <tr>
                  <td style="vertical-align:middle;white-space:nowrap;"><%= @count %> </td>
                  <td style="vertical-align:middle;white-space:nowrap;"><%= shop.name %></td>
                  <td style="vertical-align:middle;white-space:nowrap;"><%= shop.address.street + " " + shop.address.house_number + ", " + shop.address.postal_code.to_s + " " + shop.address.city + ", " + shop.address.country %></td>
                <td width="100%"></td>
                  <% if can? :show, shop %>
                      <td style="vertical-align:middle;white-space:nowrap; ">
                        <a class="btn btn-default btn-sm" href=<%= shop_path(shop) %>><i class="fa fa-search"></i> Show</a>
                      </td>
                  <% else %>
                  <td></td>
                  <% end %>
                  <% if can? :edit, shop %>
                      <td style="vertical-align:middle;white-space:nowrap; ">
                        <a class="btn btn-default btn-sm" href=<%= edit_shop_path(shop) %>><i class="fa fa-pencil"></i>
                          Edit</a>
                      </td>
                  <% else %>
                      <td></td>
                  <% end %>
                  <% if can? :delete, shop %>
                      <td style="vertical-align:middle;white-space:nowrap;" >
                        <a class="btn btn-default btn-sm" data-confirm="Are you sure?" data-method="delete" rel="nofollow" href=<%= shop_path(shop) %>><i class="fa fa-trash-o fa-lg"></i> Destroy</a>
                      </td >
                  <% else %>
                      <td></td>

                  <% end %>


                </tr>
                <% @count = @count+1 %>
            <% end %>
            </tbody>

          </table>

          <% if can? :create, Shop %>
              <%= link_to 'New Shop', new_shop_path, {:class => "btn-u btn-large"}  %>
          <% end %>

        </div>
      </div>
    </div>
  </div>
</div>

app/views/shops/new.html.erb
<div class="body">

  <% content_for :title, 'New Shop' %>
  <% navigation_add 'Shop', shops_path %>

  <div class="container">
    <div class="row-fluid">

      <%= render 'form' %>

      <div class="glyphicons-demo" style="text-align: center">
        <a class="glyphicons no-js left_arrow" href=<%= shops_path %>><i></i>Back</a>
      </div>

    </div>
  </div>
</div>

app/views/shops/show.html.erb
<% content_for :title, @shop.name %>
<% navigation_add 'Shops', shops_path %>

<div id="map" class="map margin-bottom-40">
</div>

<div class="container">
  <div class="row-fluid margin-bottom-20">

    <div class="booking-blocks">

      <div class="overflow-hidden">

        <div class="headline"><h3><%= @shop.name %></h3></div>

        <ul class="unstyled who margin-bottom-20">
          <li>
            <a><i class="fa fa-home"></i><%= @shop.address.street + " " + @shop.address.house_number + ", " + @shop.address.postal_code.to_s + " " + @shop.address.city + ", " + @shop.address.country %>
            </a></li>
          <li><a href=mailto:<%= @shop.email %>><i class="fa fa-envelope"></i><%= @shop.email %></a></li>
          <li><a><i class="fa fa-phone"></i><%= @shop.phonenumber %></a></li>
          <li><a href=<%= @shop.website %>><i class="fa fa-globe"></i><%= @shop.website %></a></li>
        </ul>

      </div>
    </div>
  </div>
</div>


<div class="container">
  <div class="row-fluid margin-bottom-20">

    <div class="booking-blocks">

      <div class="overflow-hidden">

        <div class="headline"><h3>Beers</h3></div>

        <ul class="unstyled who margin-bottom-20">
          <% @i = 0 %>
          <% @shop.beers.each do |beer| %>
              <% @i = @i +1 %>
              <li class="span3">
                <div class="thumbnail-style thumbnail-kenburn">
                  <div class="thumbnail-img">
                    <div class="myoverflow-hidden"><img style=" position: absolute;top: -9999px;bottom: -9999px;left: -9999px;right: -9999px;margin: auto;" src="<%= beer.beerURL %> " alt="" /></div>
                    <%= link_to "read more +", beer, html_options = { class: "btn-more hover-effect" } %>
                  </div>
                  <h3><a class="hover-effect" href="<%= beer_path(beer) %>>"><%= beer.title %></a></h3>
                  <p> A beer of the category <%= beer.category.name %> bottled by <%= beer.producer.name %>. Click to see ratings and more information.  </p>
                </div>
              </li>
              <% if @i == 4 %>
                  <% @i = 0 %>
                  </ul>

                  <ul class="unstyled who margin-bottom-20">
              <% end %>
          <% end %>
          </ul>

      </div>
    </div>
  </div>
</div>

<div class="container glyphicons-demo" style="text-align: center">
  <a class="glyphicons no-js left_arrow" href=<%= shops_path %>><i></i>Back</a>
  <% if can? :edit, @shop %>
      <a class="glyphicons no-js edit" href=<%= edit_shop_path(@shop) %>><i></i>Edit</a>
  <% end %>
  <% if can? :delete, @shop %>
      <a class="glyphicons no-js delete" data-confirm="Are you sure?" data-method="delete" rel="nofollow" href=<%= shop_path(@shop) %>><i></i>
        Destroy</a>
  <% end %>
</div>

<script type="text/javascript">
    Contact.initMap('<%= @shop.address.city.to_s + ' ' +  @shop.address.street.to_s + ' ' + @shop.address.house_number.to_s %>')
</script>