config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  ActiveAdmin.routes(self)

  resources :shop_beers

  resources :beers

  resources :shops
  resources :ratings
  resources :criterions

  resources :addresses

  devise_for :users, :controllers => { registrations: 'registrations' }
  resources :events

  resources :clubs
  resources :categories
  resources :producers

   root 'welcome#index'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    user ||= User.new # guest user (not logged in)
    if user.has_role?(:admin)
      #Admins
      can :manage, :all
    elsif user.has_role?(:user)
      can :create, Club
      can :create, Rating
      can :create, Criterion
      can :create, Shop
      can :create, Beer

      can :manage, Rating do |r|
        r.user_id == user.id
      end

      can :manage, Criterion do |c|
        c.rating.user_id == user.id
      end


      can :manage, Shop do |s|
       s.user_id == user.id
      end

      can :read, :all

      @clubs = Club.where(user_id: user.id)

      @clubs.each do |c|
          can :manage, c
          can :manage, Event
        end
    else
      can :read, :all

    end
    #can :create, Event, :user_id => user.id

    #

    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities

  end
end

app/models/address.rb
class Address < ActiveRecord::Base
  has_one :user
  has_one :club
  has_one :shop
  validates :street,:house_number,:city,:country,:postal_code, presence: true
end

app/models/beer.rb
class Beer < ActiveRecord::Base
  belongs_to :category
  belongs_to :producer
  has_many :shop_beers
  has_many :shops, through: :shop_beers
  has_many :ratings
  has_many :users, :through => :ratings
  accepts_nested_attributes_for :category, :producer
  mount_uploader :beerURL, ImageUploader
  #validates :title, :category_id, :producer_id, presence: true
end

app/models/beer_club.rb
class BeerClub < ActiveRecord::Base
  belongs_to :beer
  belongs_to :club
end

app/models/category.rb
class Category < ActiveRecord::Base
   has_many :beers
   validates :name, presence: :true
end

app/models/club.rb
class Club < ActiveRecord::Base
  has_many :beer_clubs
  has_many :beers, through:  :beer_clubs
  has_many :events
  belongs_to :address
  belongs_to :user
  accepts_nested_attributes_for :address, :beers, :user
  mount_uploader :clubURL, ImageUploader

end

app/models/criterion.rb
class Criterion < ActiveRecord::Base
  belongs_to :rating
  validates :value ,:inclusion => 1..5
end

app/models/event.rb
class Event < ActiveRecord::Base
  belongs_to :club
  mount_uploader :imageURL, ImageUploader
  accepts_nested_attributes_for :club
  #validates :club_id, :title, presence: true
  validates :club_id, presence: true
  before_destroy :remember_image
  after_destroy :remove_img

  protected
  def remember_image
    @image_name = self[:imageURL]
  end

  def remove_img
    if @image_name.present?
      if File.exist?(@image_name)
        File.delete(@image_name)
      end
    end
  end

end

app/models/producer.rb
class Producer < ActiveRecord::Base
  belongs_to :address
  has_many :beers
  #validates :name, :address_id, presence: :true
  accepts_nested_attributes_for :address
end

app/models/rating.rb
class Rating < ActiveRecord::Base
  has_many :criterions
  belongs_to :user
  belongs_to :beer
  accepts_nested_attributes_for :criterions
  validates :headline,:comment, presence: true
  validates_associated :criterions
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users, :join_table => :users_roles
  belongs_to :resource, :polymorphic => true
  
  scopify
end

app/models/shop.rb
class Shop < ActiveRecord::Base

  has_many :shop_beers
  has_many :beers, through: :shop_beers
  belongs_to :user
  belongs_to :address
  validates :name,:email,:phonenumber,:website, presence: true
  validates_associated :address
  accepts_nested_attributes_for :address, :user
end

app/models/shop_beer.rb
class ShopBeer < ActiveRecord::Base
  belongs_to :shop
  belongs_to :beer
end

app/models/user.rb
class User < ActiveRecord::Base
  rolify
  belongs_to :address
  has_many :ratings
  has_many :beers, :through => :ratings
  has_many :clubs
  has_many :shops
  accepts_nested_attributes_for :address

  validates :first_name,:last_name, presence: true
  validates_associated :address


  after_create :assign_default_role

  def assign_default_role
    add_role(:user)
  end

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/helpers/beers_helper.rb
module BeersHelper
end

app/helpers/clubs_helper.rb
module ClubsHelper
end

app/helpers/events_helper.rb
module EventsHelper
  require 'carrierwave/processing/mini_magick'
end

app/helpers/ratings_helper.rb
module RatingsHelper
end

app/helpers/shops_helper.rb
module ShopsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/shared/_breadcrumb.html.erb
<div class="breadcrumbs <% if current_page?(controller: shops_path, action: 'show', id: params[:id] || 0 ) %><%else%><% if current_page?(controller: clubs_path, action: 'show', id: params[:id] || 0 ) %><%else%>margin-bottom-20<% end %><%end%>">
  <div class="container">
    <h1 class="color-green pull-left"> <%=yield(:title)%> </h1>
    <ul class="pull-right breadcrumb">

  <% nav.each do |n| %>
      <li><%= link_to n[:title] , n[:url] %> <span class="divider">/</span></li>
  <% end %>
      <li class="active"><%=yield(:title)%></li>

    </ul>
  </div>
  <!--/container-->
</div>
<!--/breadcrumbs-->

app/views/shared/_footer.html.erb
<!--=== Footer ===-->
<div class="footer">
  <div class="container">
    <div class="row-fluid">
      <div class="span4">
        <!-- About -->
        <div class="headline"><h3>About</h3></div>
        <p class="margin-bottom-25">BeerToBeer is an incredibly beautiful beer rating portal for connoisseurs.</p>
        <!-- Monthly Newsletter -->
        <div class="headline"><h3>Monthly Newsletter</h3></div>
        <p>Subscribe to our newsletter and stay up to date with the latest news and deals!</p>
        <form class="form-inline" />
        <div class="input-append">
          <input type="text" placeholder="Email Address" class="input-medium" />
          <button class="btn-u">Subscribe</button>
        </div>
        </form>
      </div><!--/span4-->
      <div class="span4">
        <div class="posts">

          <div class="headline"><h3>Recent Beer Ratings</h3></div>

          <% @ratings = Rating.all.limit(3) %>
          <% @ratings.each do |rating| %>
          <dl class="dl-horizontal">
            <dt><div class="myoverflow-hidden3"><img style=" position: absolute;top: -9999px;bottom: -9999px;left: -9999px;right: -9999px;margin: auto;" src="<%= rating.beer.beerURL %> " alt="" /></div></dt>
            <dd>
              <p><a href="<%= rating_path(rating) %>">

                <% if rating.headline.length > 15 %>
                    <%= rating.headline.slice!(0..15) %>...
                <% else %>
                    <%= rating.headline %>
                <% end %>

             <br>
                <% if rating.comment.length > 15 %>
                    <%= rating.comment.slice!(0..15) %>...
                <% else %>
                    <%= rating.comment %>
                <% end %> </a></p>
            </dd>
          </dl>
          <% end %>

        </div>
      </div><!--/span4-->
      <div class="span4">
        <!-- Monthly Newsletter -->
        <div class="headline"><h3>Contact Us</h3></div>
        <address>
          18, Knoggerstraße, Germany <br />
          Nordrhein-Westfalen, DE <br />
          Phone: 0800 123 3456 <br />
          Fax: 0800 123 3456 <br />
          Email: <a href="mailto:info@beer.com" class="">info@beer.com</a>
        </address>
        <!-- Stay Connected -->
        <div class="headline"><h3>Stay Connected</h3></div>
        <ul class="social-icons">
          <li><a href="#" data-original-title="Feed" class="social_rss"></a></li>
          <li><a href="#" data-original-title="Facebook" class="social_facebook"></a></li>
          <li><a href="#" data-original-title="Twitter" class="social_twitter"></a></li>
          <li><a href="#" data-original-title="Goole Plus" class="social_googleplus"></a></li>
          <li><a href="#" data-original-title="Pinterest" class="social_pintrest"></a></li>
          <li><a href="#" data-original-title="Linkedin" class="social_linkedin"></a></li>
          <li><a href="#" data-original-title="Vimeo" class="social_vimeo"></a></li>
        </ul>
      </div><!--/span4-->
    </div><!--/row-fluid-->
  </div><!--/container-->
</div><!--/footer-->
<!--=== End Footer ===-->
<!--=== Copyright ===-->
<div class="copyright">
  <div class="container">
    <div class="row-fluid">
      <div class="span8">
        <p>2015 &copy; BeerToBeer. ALL Rights Reserved. <a>Privacy Policy</a> | <a>Terms of Service</a></p>
      </div>
      <div class="span4">
        <a href="index.html"><img id="logo-footer" src="/assets/img/ace/logo.png" class="pull-right" alt="" /></a>
      </div>
    </div><!--/row-fluid-->
  </div><!--/container-->
</div><!--/copyright-->
<!--=== End Copyright ===-->

app/views/shared/_navigation.html.erb
<!--=== Top ===-->
<div class="top">
  <div class="container">
    <ul class="loginbar pull-right">

      <% if current_user %>
          <% if current_user.has_role? :admin %>
              <li><%= link_to 'Verwaltung', admin_dashboard_path, data: { no_turbolink: true } %></li>
              <li class="devider">&nbsp;</li>
          <%end%>
          <li><%= link_to current_user.email, destroy_user_session_path, method: :delete %></li>
          <%= render partial: 'shared/options' %>
      <% else %>
          <li><%= link_to 'Sign in', new_user_session_path %></li>
          <li class="devider">&nbsp;</li>
          <li><%= link_to 'Sign up', new_user_registration_path %></li>
      <% end %>
    </ul>
  </div>
</div><!--/top-->
<!--=== End Top ===-->

<!--=== Header ===-->
<div class="header">
  <div class="container">
    <!-- Logo -->
    <div class="logo">
      <a href=<%= root_path %>><img id="logo-header" src="/assets/img/ace/logo.png" alt="Logo" /></a>
    </div><!-- /logo -->

    <!-- Menu -->
    <div class="navbar">
      <div class="navbar-inner">
        <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </a><!-- /nav-collapse -->
        <div class="nav-collapse collapse">
          <ul class="nav top-2">
            <li <% if request.env['PATH_INFO']== '/' %>class="active" <%end%> >
              <%= link_to 'Home',root_path %>
               <!-- <b class="caret"></b>-->

              <!--<ul class="dropdown-menu">
                <li class="active"><a href="index.html">Option1: Landing Page</a></li>
              </ul>-->
              <b class="caret-out"></b>
            </li>
            <li <% if request.env['PATH_INFO'].include? '/beers' %>class="active" <%end%>>
              <a href="" class="dropdown-toggle" data-toggle="dropdown">Beer
                <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to 'All Beers', beers_path %></li>
                <% if current_user %>
                <li><%= link_to 'New Beer', new_beer_path %></li>
                <%end %>
              </ul>
              <b class="caret-out"></b>
            </li>
            <li <% if request.env['PATH_INFO'].include? '/shops' %>class="active" <%end%> >
              <a href="" class="dropdown-toggle" data-toggle="dropdown">Shop
                <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to 'All Shops', shops_path %></li>
                <% if current_user %>
                <li><%= link_to 'New Shop', new_shop_path %></li>
                <%end %>
              </ul>
              <b class="caret-out"></b>
            </li>
            <li <% if request.env['PATH_INFO'].include? '/clubs' %>class="active" <%end%> >
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">Club
                <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to 'All Clubs', clubs_path %></li>
                <% if current_user %>
                <li><%= link_to 'New Club', new_club_path %></li>
                <%end %>
              </ul>
              <b class="caret-out"></b>
            </li>
            <li <% if request.env['PATH_INFO'].include? '/events' %>class="active" <%end%> >
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">Event
                <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to 'All Events', events_path %></li>
              </ul>
              <b class="caret-out"></b>
            </li>
            <li <% if request.env['PATH_INFO'].include? '/ratings' %>class="active" <%end%> >
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">Rating
                <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "All Ratings", ratings_path %></li>
                <li><%= link_to "Average Ratings", ratings_path(:type => "avg") %></li>
              </ul>
              <b class="caret-out"></b>
            </li>
          </ul>
        </div><!-- /nav-collapse -->
      </div><!-- /navbar-inner -->
    </div><!-- /navbar -->
  </div><!-- /container -->
</div><!--/header -->
<!--=== End Header ===-->

app/views/shared/_options.html.erb
<li class="dropdown menu-level1">
  <a class="dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-expanded="true">
    Optionen
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu">
    <li class="menu-level2"><%= link_to "Edit Profile",edit_user_registration_path%></li>
    <li class="menu-level2"><%= link_to "Sign out", destroy_user_session_path, method: "delete" %></li>
  </ul>
</li>