config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  ActiveAdmin.routes(self)

  resources :shop_beers

  resources :beers

  resources :shops
  resources :ratings
  resources :criterions

  resources :addresses

  devise_for :users, :controllers => { registrations: 'registrations' }
  resources :events

  resources :clubs
  resources :categories
  resources :producers

   root 'welcome#index'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    user ||= User.new # guest user (not logged in)
    if user.has_role?(:admin)
      #Admins
      can :manage, :all
    elsif user.has_role?(:user)
      can :create, Club
      can :create, Rating
      can :create, Criterion
      can :create, Shop
      can :create, Beer

      can :manage, Rating do |r|
        r.user_id == user.id
      end

      can :manage, Criterion do |c|
        c.rating.user_id == user.id
      end


      can :manage, Shop do |s|
       s.user_id == user.id
      end

      can :read, :all

      @clubs = Club.where(user_id: user.id)

      @clubs.each do |c|
          can :manage, c
          can :manage, Event
        end
    else
      can :read, :all

    end
    #can :create, Event, :user_id => user.id

    #

    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities

  end
end

app/models/address.rb
class Address < ActiveRecord::Base
  has_one :user
  has_one :club
  has_one :shop
  validates :street,:house_number,:city,:country,:postal_code, presence: true
end

app/models/beer.rb
class Beer < ActiveRecord::Base
  belongs_to :category
  belongs_to :producer
  has_many :shop_beers
  has_many :shops, through: :shop_beers
  has_many :ratings
  has_many :users, :through => :ratings
  accepts_nested_attributes_for :category, :producer
  mount_uploader :beerURL, ImageUploader
  #validates :title, :category_id, :producer_id, presence: true
end

app/models/beer_club.rb
class BeerClub < ActiveRecord::Base
  belongs_to :beer
  belongs_to :club
end

app/models/category.rb
class Category < ActiveRecord::Base
   has_many :beers
   validates :name, presence: :true
end

app/models/club.rb
class Club < ActiveRecord::Base
  has_many :beer_clubs
  has_many :beers, through:  :beer_clubs
  has_many :events
  belongs_to :address
  belongs_to :user
  accepts_nested_attributes_for :address, :beers, :user
  mount_uploader :clubURL, ImageUploader

end

app/models/criterion.rb
class Criterion < ActiveRecord::Base
  belongs_to :rating
  validates :value ,:inclusion => 1..5
end

app/models/event.rb
class Event < ActiveRecord::Base
  belongs_to :club
  mount_uploader :imageURL, ImageUploader
  accepts_nested_attributes_for :club
  #validates :club_id, :title, presence: true
  validates :club_id, presence: true
  before_destroy :remember_image
  after_destroy :remove_img

  protected
  def remember_image
    @image_name = self[:imageURL]
  end

  def remove_img
    if @image_name.present?
      if File.exist?(@image_name)
        File.delete(@image_name)
      end
    end
  end

end

app/models/producer.rb
class Producer < ActiveRecord::Base
  belongs_to :address
  has_many :beers
  #validates :name, :address_id, presence: :true
  accepts_nested_attributes_for :address
end

app/models/rating.rb
class Rating < ActiveRecord::Base
  has_many :criterions
  belongs_to :user
  belongs_to :beer
  accepts_nested_attributes_for :criterions
  validates :headline,:comment, presence: true
  validates_associated :criterions
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users, :join_table => :users_roles
  belongs_to :resource, :polymorphic => true
  
  scopify
end

app/models/shop.rb
class Shop < ActiveRecord::Base

  has_many :shop_beers
  has_many :beers, through: :shop_beers
  belongs_to :user
  belongs_to :address
  validates :name,:email,:phonenumber,:website, presence: true
  validates_associated :address
  accepts_nested_attributes_for :address, :user
end

app/models/shop_beer.rb
class ShopBeer < ActiveRecord::Base
  belongs_to :shop
  belongs_to :beer
end

app/models/user.rb
class User < ActiveRecord::Base
  rolify
  belongs_to :address
  has_many :ratings
  has_many :beers, :through => :ratings
  has_many :clubs
  has_many :shops
  accepts_nested_attributes_for :address

  validates :first_name,:last_name, presence: true
  validates_associated :address


  after_create :assign_default_role

  def assign_default_role
    add_role(:user)
  end

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/events_controller.rb
class EventsController < ApplicationController

  before_action :set_event, only: [:show, :edit, :update, :destroy]
  load_and_authorize_resource except: :create
  skip_load_and_authorize_resource only: [:new, :create]
  # GET /events
  # GET /events.json
  def index
    @events = Event.joins(:club).where('events.sdate >= ?', Date.current).where('clubs.active = ?', true)

    @events_club_inaktiv = Event.joins(:club).where('events.sdate > ?', Date.current).where('clubs.active = ?', false)

    @events_old = Event.joins(:club).where('events.sdate <=?', Date.current)
    #@events = Event.where('events.sdate > ?', Date.current)
  end

  # GET /events/1
  # GET /events/1.json
  def show
  end

  # GET /events/new
  def new
    if Club.where(user_id: current_user.id, id: params[:club_id] ).count == 1
      @event = Event.new
    elsif current_user.has_role? :admin
      @event = Event.new
    else
      authorize! :create, Event
    end

  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    #authorize! :create, Event
    @event = Event.new(event_params)



    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json


  def destroy

    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params

      params.require(:event).permit(:title, :sdate, :imageURL, :club_id)
    end
end

app/helpers/beers_helper.rb
module BeersHelper
end

app/helpers/breadcrumb_helper.rb
module BreadcrumbHelper
  def ensure_navigation
    @navigation ||= [ { :title => 'Home', :url => '/' } ]
  end

  def navigation_add(title, url)
    ensure_navigation << { :title => title, :url => url }
  end

  def render_breadcrumb
    render :partial => 'shared/breadcrumb', :locals => { :nav => ensure_navigation }
  end
end

app/helpers/clubs_helper.rb
module ClubsHelper
end

app/helpers/events_helper.rb
module EventsHelper
  require 'carrierwave/processing/mini_magick'
end

app/helpers/producers_helper.rb
module ProducersHelper
end

app/helpers/ratings_helper.rb
module RatingsHelper
end

app/helpers/shops_helper.rb
module ShopsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/events/_form.html.erb
<%= form_for(@event, html: {role: "form", class: "reg-page"}) do |f| %>
    <% if @event.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

          <ul>
            <% @event.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <h3 align="center">
      <% if current_page?(controller: events_path, action: 'edit', id: params[:id] || 0) %>Edit
          Event: <%= @event.title %>
      <% else %>Create a new Event
      <% end %></h3>

    <hr/>

    <div class="controls">
      <%= f.label :title do %>
          Name<span class="color-red"> *</span>
      <% end %>
      <%= f.text_field :title, class: "span12" %>
    </div>

    <div class="controls">
      <%= f.label :sdate do %>
          Date<span class="color-red"> *</span>
      <% end %>
      <%= f.date_select :sdate, class: "span12" %>
    </div>

    <div class="controls">
      <%= f.label :sdate, :ignore_date => true do %>
          Time<span class="color-red"> *</span>
      <% end %>
      <%= f.time_select :sdate, :ignore_date => true, class: "span12" %>
    </div>

    <div class="controls">
      <%= f.label :imageURL do %>
          Flyer<span class="color-red"> *</span>
      <% end %>
      <%= f.file_field :imageURL, class: "span12" %>
    </div>


    <div class="controls">
      <%= f.label :club_id do %>
          Club<span class="color-red"> *</span>
      <% end %>
      <% if current_user %>
          <% if current_user.has_role? :admin %>
              <%= f.collection_select :club_id, Club.all, :id, :name,
                                      if (params[:club_id])
                                        {selected: params[:club_id]}
                                      else
                                        {selected: @event.club_id}
                                      end
              %>
          <% else %>
              <%= f.collection_select :club_id, Club.where(:user_id => current_user.id), :id, :name, if (params)
                                                                                                       {selected: params[:club_id]}
                                                                                                     else
                                                                                                       {selected: @event.club.id}
                                                                                                     end %>
          <% end %>
          </div>

      <% end %>

      <hr>
      <br>

      <div class="controls form-inline">
        <input type="checkbox">
        <label class="checkbox" style="padding-top: 4.5px; padding-left: 5px">
          I read <a class="color-green">Terms and Conditions</a>
        </label>
        <%= f.submit class: "btn-u pull-right" %>
      </div>


<% end %>

app/views/events/edit.html.erb
<div class="body">

  <% content_for :title, 'Edit Event' %>
  <% navigation_add 'Events', events_path %>

  <div class="container">
    <div class="row-fluid">

      <%= render 'form' %>

      <div class="glyphicons-demo" style="text-align: center">
        <a class="glyphicons no-js left_arrow" href=<%= events_path %>><i></i>Back</a>
        <a class="glyphicons no-js file" href=<%= event_path %>><i></i>Show</a>
      </div>

    </div>
  </div>
</div>

app/views/events/index.html.erb
<% content_for :title, 'Events' %>

<div class="container">
  <div class="row-fluid">
    <div class="row-fluid margin-bottom-20">
      <div class="booking-blocks">
        <div class="overflow-hidden">

          <div class="headline"><h3>All Events</h3></div>
          <% if current_user %>
              <% if current_user.has_role? :admin %>
                  <div>
                    <table class="table table-hover">
                      <tr>
                        <th align="left">Events of inaktiv Clubs</th>
                        <th></th>
                        <th></th>
                        <th></th>
                        <th></th>
                        <th></th>
                      </tr>
                      <% @events_club_inaktiv.each do |event| %>
                          <tr>
                            <td width="20%" align="left"><%= event.title %></td>
                            <td width="20%" align="left"><%= event.sdate.to_date.to_s(:rfc822) %></td>
                            <td width="20%" align="left"><%= event.sdate.to_s(:time) %></td>
                            <td width="20%" align="left"><%= link_to event.club.name, event.club %></td>
                            <td width="10%" align="left" style="vertical-align:middle;white-space:nowrap; ">
                               <a class="btn btn-default btn-sm" href=<%= event_path(event) %>><i class="fa fa-search"></i> Show</a>
                            </td>
                            <td width="10%" align="left" style="vertical-align:middle;white-space:nowrap; ">
                              <a class="btn btn-default btn-sm" href=<%= edit_event_path(event) %>><i class="fa fa-pencil"></i>
                                Edit</a>
                            </td>
                            <td width="10%" align="left" style="vertical-align:middle;white-space:nowrap;">
                              <a class="btn btn-default btn-sm" data-confirm="Are you sure?" data-method="delete" rel="nofollow" href=<%= event_path(event) %>><i class="fa fa-trash-o fa-lg"></i>
                                Destroy</a>
                            </td>
                          </tr>
                      <% end %>
                    </table>
                  </div>
                  <div>

                    <table width="100%">
                      <tr>
                        <th align="left">Expired Events</th>
                        <th></th>
                        <th></th>
                        <th></th>
                        <th></th>
                      </tr>
                      <% @events_old.each do |event| %>
                          <tr>
                            <td width="20%" align="left"><%= event.title %></td>
                            <td width="20%" align="left"><%= event.sdate.to_date.to_s(:rfc822) %></td>
                            <td width="20%" align="left"><%= event.sdate.to_s(:time) %></td>
                            <td width="20%" align="left"><%= event.club.name %></td>
                            <td width="10%" align="left" style="vertical-align:middle;white-space:nowrap; ">
                              <a class="btn btn-default btn-sm" href=<%= event_path(event) %>><i class="fa fa-search"></i> Show</a>
                            </td>
                            <td width="10%" align="left" style="vertical-align:middle;white-space:nowrap; ">
                              <a class="btn btn-default btn-sm" href=<%= edit_event_path(event) %>><i class="fa fa-pencil"></i>
                                Edit</a>
                            </td>
                            <td width="10%" align="left" style="vertical-align:middle;white-space:nowrap;">
                              <a class="btn btn-default btn-sm" data-confirm="Are you sure?" data-method="delete" rel="nofollow" href=<%= event_path(event) %>><i class="fa fa-trash-o fa-lg"></i>
                                Destroy</a>
                            </td>
                          </tr>
                      <% end %>
                    </table>
                  </div>
              <% end %>
          <% end %>


          <div>
            <% i = 0 %>
            <% @events.each do |event| %>

                <% if (i%3 == 0) %>
                    <div>
                      <ul class="thumbnails">

                <% end %>
                <li class="span4">
                  <div class="thumbnail thumbnail-kenburn">
                    <div class="overflow-hidden">
                      <%= link_to (image_tag event.imageURL, size: "400x700", alt: "#{event.title} Bild"), event %>
                    </div>
                    <div class="caption">
                      <h3><%= link_to event.title, event %></h3>

                      <p>Date: <%= event.sdate.to_date.to_s(:rfc822) %></p>

                      <p>Starttime: <%= event.sdate.to_s(:time) %></p>

                      <p>Location: <%= link_to event.club.name, event.club %></p>

                      <div class="container glyphicons-demo">
                        <% if can? :update, event %>
                            <a class="glyphicons no-js edit" href=<%=  edit_event_path(event) %>><i></i>Edit</a>
                        <% end %>
                        <% if can? :delete, event %>
                            <a class="glyphicons no-js delete" data-confirm="Are you sure?" data-method="delete" rel="nofollow" href=<%= event_path(event) %>><i></i>
                              Destroy</a>
                        <% end %>
                      </div>
                      </div>


                    </div>

                </li>
                <% if (i%3 == 2) or (i == @events.count-1) %>

                    </ul>
                    </div>
                <% end %>
                <% i+= 1 %>
            <% end %>
            <br>


            <% if can? :create, Event %>
                <%= link_to 'New Event', new_event_path, {:class => "btn-u btn-large"} %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/events/new.html.erb
<div class="body">

  <% content_for :title, 'New Event' %>
  <% navigation_add 'Events', events_path %>

  <div class="container">
    <div class="row-fluid">

      <%= render 'form' %>

      <div class="glyphicons-demo" style="text-align: center">
        <a class="glyphicons no-js left_arrow" href=<%= events_path %>><i></i>Back</a>
      </div>

    </div>
  </div>
</div>

app/views/events/show.html.erb
<% content_for :title, "Events" %>
<% navigation_add 'Events', events_path %>

<div class="container">
  <div class="row-fluid margin-bottom-20">

    <div class="booking-blocks">

      <div class="overflow-hidden">

        <div class="headline"><h3><%= @event.title %></h3></div>

        <div class="overflow-hidden span4">
          <%= image_tag @event.imageURL, size: "300x300", alt: "#{@event.title} Bild" %>
        </div>
        <div class="caption">
          <h3><%= "Name: " + @event.title %></h3>

          <p>Date: <%= @event.sdate.to_date.to_s(:rfc822) %></p>

          <p>Starttime: <%= @event.sdate.to_s(:time) %></p>

          <p>Location: <%= @event.club.name %></p>
        </div>
      </div>

    </div>

    <div class="container glyphicons-demo" style="text-align: center">
      <a class="glyphicons no-js left_arrow" href=<%= events_path %>><i></i>Back</a>
      <% if can? :update, @event %>
          <a class="glyphicons no-js edit" href=<%= edit_event_path(@event) %>><i></i>Edit</a>
      <% end %>
      <% if can? :delete, @event %>
          <a class="glyphicons no-js delete" data-confirm="Are you sure?" data-method="delete" rel="nofollow" href=<%= event_path(@event) %>><i></i>
            Destroy</a>
      <% end %>
    </div>
  </div>
</div>