config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  ActiveAdmin.routes(self)

  resources :shop_beers

  resources :beers

  resources :shops
  resources :ratings
  resources :criterions

  resources :addresses

  devise_for :users, :controllers => { registrations: 'registrations' }
  resources :events

  resources :clubs
  resources :categories
  resources :producers

   root 'welcome#index'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    user ||= User.new # guest user (not logged in)
    if user.has_role?(:admin)
      #Admins
      can :manage, :all
    elsif user.has_role?(:user)
      can :create, Club
      can :create, Rating
      can :create, Criterion
      can :create, Shop
      can :create, Beer

      can :manage, Rating do |r|
        r.user_id == user.id
      end

      can :manage, Criterion do |c|
        c.rating.user_id == user.id
      end


      can :manage, Shop do |s|
       s.user_id == user.id
      end

      can :read, :all

      @clubs = Club.where(user_id: user.id)

      @clubs.each do |c|
          can :manage, c
          can :manage, Event
        end
    else
      can :read, :all

    end
    #can :create, Event, :user_id => user.id

    #

    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities

  end
end

app/models/address.rb
class Address < ActiveRecord::Base
  has_one :user
  has_one :club
  has_one :shop
  validates :street,:house_number,:city,:country,:postal_code, presence: true
end

app/models/beer.rb
class Beer < ActiveRecord::Base
  belongs_to :category
  belongs_to :producer
  has_many :shop_beers
  has_many :shops, through: :shop_beers
  has_many :ratings
  has_many :users, :through => :ratings
  accepts_nested_attributes_for :category, :producer
  mount_uploader :beerURL, ImageUploader
  #validates :title, :category_id, :producer_id, presence: true
end

app/models/beer_club.rb
class BeerClub < ActiveRecord::Base
  belongs_to :beer
  belongs_to :club
end

app/models/category.rb
class Category < ActiveRecord::Base
   has_many :beers
   validates :name, presence: :true
end

app/models/club.rb
class Club < ActiveRecord::Base
  has_many :beer_clubs
  has_many :beers, through:  :beer_clubs
  has_many :events
  belongs_to :address
  belongs_to :user
  accepts_nested_attributes_for :address, :beers, :user
  mount_uploader :clubURL, ImageUploader

end

app/models/criterion.rb
class Criterion < ActiveRecord::Base
  belongs_to :rating
  validates :value ,:inclusion => 1..5
end

app/models/event.rb
class Event < ActiveRecord::Base
  belongs_to :club
  mount_uploader :imageURL, ImageUploader
  accepts_nested_attributes_for :club
  #validates :club_id, :title, presence: true
  validates :club_id, presence: true
  before_destroy :remember_image
  after_destroy :remove_img

  protected
  def remember_image
    @image_name = self[:imageURL]
  end

  def remove_img
    if @image_name.present?
      if File.exist?(@image_name)
        File.delete(@image_name)
      end
    end
  end

end

app/models/producer.rb
class Producer < ActiveRecord::Base
  belongs_to :address
  has_many :beers
  #validates :name, :address_id, presence: :true
  accepts_nested_attributes_for :address
end

app/models/rating.rb
class Rating < ActiveRecord::Base
  has_many :criterions
  belongs_to :user
  belongs_to :beer
  accepts_nested_attributes_for :criterions
  validates :headline,:comment, presence: true
  validates_associated :criterions
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users, :join_table => :users_roles
  belongs_to :resource, :polymorphic => true
  
  scopify
end

app/models/shop.rb
class Shop < ActiveRecord::Base

  has_many :shop_beers
  has_many :beers, through: :shop_beers
  belongs_to :user
  belongs_to :address
  validates :name,:email,:phonenumber,:website, presence: true
  validates_associated :address
  accepts_nested_attributes_for :address, :user
end

app/models/shop_beer.rb
class ShopBeer < ActiveRecord::Base
  belongs_to :shop
  belongs_to :beer
end

app/models/user.rb
class User < ActiveRecord::Base
  rolify
  belongs_to :address
  has_many :ratings
  has_many :beers, :through => :ratings
  has_many :clubs
  has_many :shops
  accepts_nested_attributes_for :address

  validates :first_name,:last_name, presence: true
  validates_associated :address


  after_create :assign_default_role

  def assign_default_role
    add_role(:user)
  end

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/beers_controller.rb
class BeersController < ApplicationController
  before_action :set_beer, only: [:show, :edit, :update, :destroy]
  # load_and_authorize_resource
  # GET /beers
  # GET /beers.json

  def index
    @beers = Beer.all
  end

  # GET /beers/1
  # GET /beers/1.json
  def show
  end

  # GET /beers/new
  def new
    @beer = Beer.new
    category = @beer.build_category
    producer = @beer.build_producer
  end

  # GET /beers/1/edit
  def edit
  end

  # POST /beers
  # POST /beers.json
  def create
    @beer = Beer.new(beer_params)

    respond_to { |format|
      if @beer.save
        format.html { redirect_to @beer, notice: "Beer was successfully created." }
        format.json { render :show, status: :ok, location: @beer }
      else
        format.html { render :new }
        format.json { render json: @beer.errors, status: :unprocessable_entity }
      end
    }
  end

  # PATCH/PUT /beers/1
  # PATCH/PUT /beers/1.json
  def update
    respond_to do |format|
      if @beer.update(beer_params)
        format.html { redirect_to @beer, notice: 'Beer was successfully updated.' }
        format.json { render :'clubs/index', status: :ok, location: @beer }
      else
        format.html { render :edit }
        format.json { render json: @beer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /beers/1
  # DELETE /beers/1.json
  def destroy
    @beer.destroy
    respond_to do |format|
      format.html { redirect_to beers_url, notice: 'Beer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
    def set_beer
      @beer = Beer.find(params[:id])
    end

  # Never trust parameters from the scary internet, only allow the white list through.
    def beer_params
      params.require(:beer).permit(:title, :beerURL ,category_attributes: [:name], producer_attributes: [:name])
    end
end

app/helpers/beers_helper.rb
module BeersHelper
end

app/helpers/breadcrumb_helper.rb
module BreadcrumbHelper
  def ensure_navigation
    @navigation ||= [ { :title => 'Home', :url => '/' } ]
  end

  def navigation_add(title, url)
    ensure_navigation << { :title => title, :url => url }
  end

  def render_breadcrumb
    render :partial => 'shared/breadcrumb', :locals => { :nav => ensure_navigation }
  end
end

app/helpers/clubs_helper.rb
module ClubsHelper
end

app/helpers/events_helper.rb
module EventsHelper
  require 'carrierwave/processing/mini_magick'
end

app/helpers/producers_helper.rb
module ProducersHelper
end

app/helpers/ratings_helper.rb
module RatingsHelper
end

app/helpers/shops_helper.rb
module ShopsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/beers/_form.html.erb
<%= form_for(@beer, html: {role: "form", class: "reg-page"}) do |f| %>
    <% if @beer.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@beer.errors.count, "error") %> prohibited this beer from being saved:</h2>

          <ul>
            <% @beer.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <h3 align="center">
      <% if current_page?(controller: beers_path, action: 'edit', id: params[:id] || 0) %>Edit Beer: <%= @beer.title %>
      <% else %>Create a new Beer
      <% end %></h3>

    <hr/>
    <div class="controls">
      <%= f.label :title do %>
          Name<span class="color-red"> *</span>
      <% end %>
      <%= f.text_field :title, class: "span12" %>
    </div>

    <div class="controls">
      <%= f.fields_for :category do |info| %>
          <%= info.label :category do %>
              Category<span class="color-red"> *</span>
          <% end %>
          <%= info.text_field :name, class: "span12" %>
      <% end %>
    </div>

    <div class="controls">
      <%= f.fields_for :producer do |info2| %>
         <%= info2.label :producer do %>
              Producer<span class="color-red"> *</span>
          <% end %>
          <%= info2.text_field :name, class: "span12" %>

      <% end %>
    </div>

    <div class="controls">
      <%= f.label "Image" %>
      <%= f.file_field :beerURL %>
    </div>

    <hr/>
    <br>

    <div class="controls form-inline">
      <input type="checkbox">
      <label class="checkbox" style="padding-top: 4.5px; padding-left: 5px">
        I read <a class="color-green">Terms and Conditions</a>
      </label>
      <%= f.submit class: "btn-u pull-right" %>
    </div>

<% end %>

app/views/beers/edit.html.erb
<div class="body">

  <% content_for :title, 'Edit Beer' %>
  <% navigation_add 'Beers', beers_path %>

  <div class="container">
    <div class="row-fluid">

      <%= render 'form' %>

      <div class="glyphicons-demo"  style="text-align: center">
        <a class="glyphicons no-js left_arrow" href=<%= beers_path %>><i></i>Back</a>
        <a class="glyphicons no-js file" href=<%= beer_path %>><i></i>Show</a>
      </div>

    </div>
  </div>
</div>

app/views/beers/index.html.erb
<% content_for :title, 'Beers' %>

<div class="container">
  <div class="row-fluid">
    <div class="row-fluid margin-bottom-20">
      <div class="booking-blocks">
        <div class="overflow-hidden">

          <div class="headline"><h3>All Beers</h3></div>

          <table class="table table-hover">
            <thead>
            <tr>
              <th>Title</th>
              <th></th>
              <th>Category</th>
              <th></th>
              <th>Producer</th>
            </tr>
            </thead>

            <tbody>
            <% @beers.each do |beer| %>
                <tr>
                  <td style="vertical-align:middle;white-space:nowrap;"><%= beer.title %></td>
                  <td></td>
                  <td style="vertical-align:middle;white-space:nowrap;"><%= beer.category.name %></td>
                  <td></td>
                  <td style="vertical-align:middle;white-space:nowrap;"><%= beer.producer.name %></td>
                  <td width="100%"></td>
                  <% if can? :show, beer %>
                      <td style="vertical-align:middle;white-space:nowrap; ">
                        <a class="btn btn-default btn-sm" href=<%= beer_path(beer) %>><i class="fa fa-search"></i> Show</a>
                      </td>
                  <% else %>
                      <td></td>
                  <% end %>
                  <% if can? :edit, beer %>
                      <td style="vertical-align:middle;white-space:nowrap; ">
                        <a class="btn btn-default btn-sm" href=<%= edit_beer_path(beer) %>><i class="fa fa-pencil"></i>
                          Edit</a>
                      </td>
                  <% else %>
                      <td></td>
                  <% end %>
                  <% if can? :delete, beer %>
                      <td style="vertical-align:middle;white-space:nowrap;">
                        <a class="btn btn-default btn-sm" data-confirm="Are you sure?" data-method="delete" rel="nofollow" href=<%= beer_path(beer) %>><i class="fa fa-trash-o fa-lg"></i>
                          Destroy</a>
                      </td>
                  <% else %>
                      <td></td>

                  <% end %>


                </tr>
            <% end %>
            </tbody>
          </table>

          <br>

          <% if can? :create, Beer %>
              <%= link_to 'New Beer', new_beer_path, {:class => "btn-u btn-large"} %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/beers/new.html.erb
<div class="body">

  <% content_for :title, 'New Beer' %>
  <% navigation_add 'Beers', beers_path %>

  <div class="container">
    <div class="row-fluid">

      <%= render 'form' %>

      <div class="glyphicons-demo"  style="text-align: center">
        <a class="glyphicons no-js left_arrow" href=<%= beers_path %>><i></i>Back</a>
      </div>

    </div>
  </div>
</div>

app/views/beers/show.html.erb
<% content_for :title, @beer.title %>
<% navigation_add 'Beers', beers_path %>
<div class="container">
  <div class="row">

    <div id="facts" class="booking-blocks " style="float: right; margin-left: 20px; width:auto !important"  >

      <div class="overflow-hidden">
        <%= image_tag @beer.beerURL, size: "200x200", alt: "#{@beer.title} Bild" %>


        <div class="headline"><h3>Facts</h3></div>
        <div class="glyphicons-demo">
          <a class="glyphicons no-js show_big_thumbnails" href="#"><i></i><strong>Category:</strong><%= @beer.category.name %></a>
          <br>
          <a class="glyphicons no-js beer" href="#"><i></i> <strong>Producer:</strong><%= @beer.producer.name %></a>
        </div>
      </div>
      <div>
      </div>
    </div>
    <% @ratings = Rating.all.where(beer_id: @beer.id) %>
    <% @ratings.each do |rating| %>
        <div id="rating" class=" booking-blocks" style="min-width:40%; width:auto !important">
          <div style="overflow:hidden;">
            <ul class="unstyled inline">
              <% @avg = rating.criterions.sum(:value)/3 %>
              <li><i class="fa fa-star<% if (@avg < 1) %>-o<% end %>"></i></li>
              <li><i class="fa fa-star<% if (@avg < 2) %>-o<% end %>"></i></li>
              <li><i class="fa fa-star<% if (@avg < 3) %>-o<% end %>"></i></li>
              <li><i class="fa fa-star<% if (@avg < 4) %>-o<% end %>"></i></li>
              <li><i class="fa fa-star<% if (@avg < 5) %>-o<% end %>"></i></li>
              <li><p>   </p></li>
              <li><b style="font-size:110%"><%= rating.headline %></b></li>
            </ul>
            <p>
            <% if rating.comment.length > 150 %>
                <%= rating.comment.slice!(0..150) %>...
                <a href="#">read more</a>
            <% else %>
                <%= rating.comment %>
            <% end %>
            </p>
            <p>
            <%= link_to "By " + rating.user.first_name + " " + rating.user.last_name + " on " + rating.created_at.to_date.to_s, rating %>
            </p>
          </div>
        </div>
    <% end %>

    <div class="container glyphicons-demo" style="text-align: center">
      <a class="glyphicons no-js left_arrow" href=<%= beers_path %>><i></i>Back</a>
      <% if can? :edit, Beer %>
          <a class="glyphicons no-js edit" href=<%= edit_beer_path(@beer) %>><i></i>Edit</a>
      <% end %>
      <% if can? :create, Rating %>
          <a class="glyphicons no-js star" href=<%= new_rating_path(:beer_id => @beer.id) %>><i></i>Rate</a>
      <% end %>
      <% if can? :delete, @beer %>
          <a class="glyphicons no-js delete" data-confirm="Are you sure?" data-method="delete" rel="nofollow" href=<%= beer_path(@beer) %>><i></i>
            Destroy</a>
      <% end %>
    </div>

  </div>
</div>
<script>
    $(window).resize(function() {
        if ($(window).width() < 540){
            $("#facts").css("float", "left");
            $("#facts").css("margin-left", "0px");
            $("#facts").css("margin-right", "20px");
        }
        else{$("#facts").css("float", "right");$("#facts").css("margin-left", "20px");$("#facts").css("margin-right", "0px");}
    });
</script>